# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0

import _cython_3_2_5
import enum
from typing import Any, Callable, ClassVar

__pyx_capi__: dict
__test__: dict
check_status: _cython_3_2_5.cython_function_or_method
config_create: _cython_3_2_5.cython_function_or_method
config_destroy: _cython_3_2_5.cython_function_or_method
config_get: _cython_3_2_5.cython_function_or_method
config_set: _cython_3_2_5.cython_function_or_method
create: _cython_3_2_5.cython_function_or_method
create_mg: _cython_3_2_5.cython_function_or_method
data_create: _cython_3_2_5.cython_function_or_method
data_destroy: _cython_3_2_5.cython_function_or_method
data_get: _cython_3_2_5.cython_function_or_method
data_set: _cython_3_2_5.cython_function_or_method
destroy: _cython_3_2_5.cython_function_or_method
execute: _cython_3_2_5.cython_function_or_method
get_config_param_dtype: _cython_3_2_5.cython_function_or_method
get_data_param_dtype: _cython_3_2_5.cython_function_or_method
get_device_mem_handler: _cython_3_2_5.cython_function_or_method
get_property: _cython_3_2_5.cython_function_or_method
logger_force_disable: _cython_3_2_5.cython_function_or_method
logger_open_file: _cython_3_2_5.cython_function_or_method
logger_set_level: _cython_3_2_5.cython_function_or_method
logger_set_mask: _cython_3_2_5.cython_function_or_method
matrix_create_batch_csr: _cython_3_2_5.cython_function_or_method
matrix_create_batch_dn: _cython_3_2_5.cython_function_or_method
matrix_create_csr: _cython_3_2_5.cython_function_or_method
matrix_create_dn: _cython_3_2_5.cython_function_or_method
matrix_destroy: _cython_3_2_5.cython_function_or_method
matrix_get_batch_csr: _cython_3_2_5.cython_function_or_method
matrix_get_batch_dn: _cython_3_2_5.cython_function_or_method
matrix_get_csr: _cython_3_2_5.cython_function_or_method
matrix_get_distribution_row1d: _cython_3_2_5.cython_function_or_method
matrix_get_dn: _cython_3_2_5.cython_function_or_method
matrix_get_format: _cython_3_2_5.cython_function_or_method
matrix_set_batch_csr_pointers: _cython_3_2_5.cython_function_or_method
matrix_set_batch_values: _cython_3_2_5.cython_function_or_method
matrix_set_csr_pointers: _cython_3_2_5.cython_function_or_method
matrix_set_distribution_row1d: _cython_3_2_5.cython_function_or_method
matrix_set_values: _cython_3_2_5.cython_function_or_method
set_async_workspace_allocator: _cython_3_2_5.cython_function_or_method
set_comm_layer: _cython_3_2_5.cython_function_or_method
set_device_mem_handler: _cython_3_2_5.cython_function_or_method
set_mg_streams: _cython_3_2_5.cython_function_or_method
set_stream: _cython_3_2_5.cython_function_or_method
set_threading_layer: _cython_3_2_5.cython_function_or_method

class ConfigParam(enum.IntEnum):
    """
    See `cudssConfigParam_t`.
    """
    __new__: ClassVar[Callable] = ...
    DETERMINISTIC_MODE: ClassVar[ConfigParam] = ...
    DEVICE_COUNT: ClassVar[ConfigParam] = ...
    DEVICE_INDICES: ClassVar[ConfigParam] = ...
    FACTORIZATION_ALG: ClassVar[ConfigParam] = ...
    HOST_NTHREADS: ClassVar[ConfigParam] = ...
    HYBRID_DEVICE_MEMORY_LIMIT: ClassVar[ConfigParam] = ...
    HYBRID_EXECUTE_MODE: ClassVar[ConfigParam] = ...
    HYBRID_MEMORY_MODE: ClassVar[ConfigParam] = ...
    IR_N_STEPS: ClassVar[ConfigParam] = ...
    IR_TOL: ClassVar[ConfigParam] = ...
    MATCHING_ALG: ClassVar[ConfigParam] = ...
    MAX_LU_NNZ: ClassVar[ConfigParam] = ...
    ND_NLEVELS: ClassVar[ConfigParam] = ...
    ND_UBFACTOR: ClassVar[ConfigParam] = ...
    PIVOT_EPSILON: ClassVar[ConfigParam] = ...
    PIVOT_EPSILON_ALG: ClassVar[ConfigParam] = ...
    PIVOT_THRESHOLD: ClassVar[ConfigParam] = ...
    PIVOT_TYPE: ClassVar[ConfigParam] = ...
    REORDERING_ALG: ClassVar[ConfigParam] = ...
    SCHUR_MODE: ClassVar[ConfigParam] = ...
    SOLVE_ALG: ClassVar[ConfigParam] = ...
    SOLVE_MODE: ClassVar[ConfigParam] = ...
    UBATCH_INDEX: ClassVar[ConfigParam] = ...
    UBATCH_SIZE: ClassVar[ConfigParam] = ...
    USE_CUDA_REGISTER_MEMORY: ClassVar[ConfigParam] = ...
    USE_SUPERPANELS: ClassVar[ConfigParam] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class DataParam(enum.IntEnum):
    """
    See `cudssDataParam_t`.
    """
    __new__: ClassVar[Callable] = ...
    COMM_DEVICE: ClassVar[DataParam] = ...
    COMM_HOST: ClassVar[DataParam] = ...
    DIAG: ClassVar[DataParam] = ...
    FLOPS: ClassVar[DataParam] = ...
    HYBRID_DEVICE_MEMORY_MIN: ClassVar[DataParam] = ...
    INERTIA: ClassVar[DataParam] = ...
    INFO: ClassVar[DataParam] = ...
    IR_N_STEPS: ClassVar[DataParam] = ...
    LU_NNZ: ClassVar[DataParam] = ...
    MEMORY_ESTIMATES: ClassVar[DataParam] = ...
    ND_PARTITION_TREE: ClassVar[DataParam] = ...
    NPIVOTS: ClassVar[DataParam] = ...
    NSUPERPANELS: ClassVar[DataParam] = ...
    PERM_COL: ClassVar[DataParam] = ...
    PERM_MATCHING: ClassVar[DataParam] = ...
    PERM_REORDER_COL: ClassVar[DataParam] = ...
    PERM_REORDER_ROW: ClassVar[DataParam] = ...
    PERM_ROW: ClassVar[DataParam] = ...
    SCALE_COL: ClassVar[DataParam] = ...
    SCALE_ROW: ClassVar[DataParam] = ...
    SCHUR_MATRIX: ClassVar[DataParam] = ...
    SCHUR_SHAPE: ClassVar[DataParam] = ...
    UBATCH_MASK: ClassVar[DataParam] = ...
    USER_HOST_INTERRUPT: ClassVar[DataParam] = ...
    USER_ND_PARTITION_TREE: ClassVar[DataParam] = ...
    USER_PERM: ClassVar[DataParam] = ...
    USER_SCHUR_INDICES: ClassVar[DataParam] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class DataType(enum.IntEnum):
    """
    See `cudssDataType_t`.
    """
    __new__: ClassVar[Callable] = ...
    C_32F: ClassVar[DataType] = ...
    C_64F: ClassVar[DataType] = ...
    R_32F: ClassVar[DataType] = ...
    R_32I: ClassVar[DataType] = ...
    R_64F: ClassVar[DataType] = ...
    R_64F_64F: ClassVar[DataType] = ...
    R_64I: ClassVar[DataType] = ...
    UNSET: ClassVar[DataType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class FactorizationAlg(enum.IntEnum):
    """
    See `cudssFactorizationAlg_t`.
    """
    __new__: ClassVar[Callable] = ...
    DEFAULT: ClassVar[FactorizationAlg] = ...
    GENERAL: ClassVar[FactorizationAlg] = ...
    MULTIBLOCK: ClassVar[FactorizationAlg] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class IndexBase(enum.IntEnum):
    """
    See `cudssIndexBase_t`.
    """
    __new__: ClassVar[Callable] = ...
    ONE: ClassVar[IndexBase] = ...
    ZERO: ClassVar[IndexBase] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class Layout(enum.IntEnum):
    """
    See `cudssLayout_t`.
    """
    __new__: ClassVar[Callable] = ...
    COL_MAJOR: ClassVar[Layout] = ...
    ROW_MAJOR: ClassVar[Layout] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class MatchingAlg(enum.IntEnum):
    """
    See `cudssMatchingAlg_t`.
    """
    __new__: ClassVar[Callable] = ...
    AUTO: ClassVar[MatchingAlg] = ...
    MAX_DIAG_COUNT: ClassVar[MatchingAlg] = ...
    MAX_DIAG_PRODUCT: ClassVar[MatchingAlg] = ...
    MAX_DIAG_SUM: ClassVar[MatchingAlg] = ...
    MAX_MIN_DIAG: ClassVar[MatchingAlg] = ...
    MAX_MIN_DIAG_ALT: ClassVar[MatchingAlg] = ...
    NONE: ClassVar[MatchingAlg] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class MatrixFormat(enum.IntEnum):
    """
    See `cudssMatrixFormat_t`.
    """
    __new__: ClassVar[Callable] = ...
    BATCH: ClassVar[MatrixFormat] = ...
    CSR: ClassVar[MatrixFormat] = ...
    DENSE: ClassVar[MatrixFormat] = ...
    DISTRIBUTED: ClassVar[MatrixFormat] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class MatrixType(enum.IntEnum):
    """
    See `cudssMatrixType_t`.
    """
    __new__: ClassVar[Callable] = ...
    GENERAL: ClassVar[MatrixType] = ...
    HERMITIAN: ClassVar[MatrixType] = ...
    HPD: ClassVar[MatrixType] = ...
    SPD: ClassVar[MatrixType] = ...
    SYMMETRIC: ClassVar[MatrixType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class MatrixViewType(enum.IntEnum):
    """
    See `cudssMatrixViewType_t`.
    """
    __new__: ClassVar[Callable] = ...
    FULL: ClassVar[MatrixViewType] = ...
    LOWER: ClassVar[MatrixViewType] = ...
    UPPER: ClassVar[MatrixViewType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class OpType(enum.IntEnum):
    """
    See `cudssOpType_t`.
    """
    __new__: ClassVar[Callable] = ...
    MAX: ClassVar[OpType] = ...
    MIN: ClassVar[OpType] = ...
    SUM: ClassVar[OpType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class Phase(enum.IntEnum):
    """
    See `cudssPhase_t`.
    """
    __new__: ClassVar[Callable] = ...
    ANALYSIS: ClassVar[Phase] = ...
    FACTORIZATION: ClassVar[Phase] = ...
    REFACTORIZATION: ClassVar[Phase] = ...
    REORDERING: ClassVar[Phase] = ...
    SOLVE: ClassVar[Phase] = ...
    SOLVE_BWD: ClassVar[Phase] = ...
    SOLVE_BWD_PERM: ClassVar[Phase] = ...
    SOLVE_DIAG: ClassVar[Phase] = ...
    SOLVE_FWD: ClassVar[Phase] = ...
    SOLVE_FWD_PERM: ClassVar[Phase] = ...
    SOLVE_REFINEMENT: ClassVar[Phase] = ...
    SYMBOLIC_FACTORIZATION: ClassVar[Phase] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class PivotEpsilonAlg(enum.IntEnum):
    """
    See `cudssPivotEpsilonAlg_t`.
    """
    __new__: ClassVar[Callable] = ...
    DEFAULT: ClassVar[PivotEpsilonAlg] = ...
    SCALED: ClassVar[PivotEpsilonAlg] = ...
    STATIC: ClassVar[PivotEpsilonAlg] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class PivotType(enum.IntEnum):
    """
    See `cudssPivotType_t`.
    """
    __new__: ClassVar[Callable] = ...
    PIVOT_AUTO: ClassVar[PivotType] = ...
    PIVOT_BUNCH_KAUFMAN: ClassVar[PivotType] = ...
    PIVOT_DIAGONAL: ClassVar[PivotType] = ...
    PIVOT_GLOBAL_COL: ClassVar[PivotType] = ...
    PIVOT_GLOBAL_ROW: ClassVar[PivotType] = ...
    PIVOT_LOCAL_BLOCK: ClassVar[PivotType] = ...
    PIVOT_NONE: ClassVar[PivotType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class ReorderingAlg(enum.IntEnum):
    """
    See `cudssReorderingAlg_t`.
    """
    __new__: ClassVar[Callable] = ...
    AMD: ClassVar[ReorderingAlg] = ...
    BTF_COLAMD: ClassVar[ReorderingAlg] = ...
    COLAMD: ClassVar[ReorderingAlg] = ...
    DEFAULT: ClassVar[ReorderingAlg] = ...
    NESTED_DISSECTION: ClassVar[ReorderingAlg] = ...
    NONE: ClassVar[ReorderingAlg] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class SolveAlg(enum.IntEnum):
    """
    See `cudssSolveAlg_t`.
    """
    __new__: ClassVar[Callable] = ...
    DEFAULT: ClassVar[SolveAlg] = ...
    GENERAL: ClassVar[SolveAlg] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class Status(enum.IntEnum):
    """
    See `cudssStatus_t`.
    """
    __new__: ClassVar[Callable] = ...
    ALLOC_FAILED: ClassVar[Status] = ...
    EXECUTION_FAILED: ClassVar[Status] = ...
    INTERNAL_ERROR: ClassVar[Status] = ...
    INVALID_VALUE: ClassVar[Status] = ...
    IR_FAILED: ClassVar[Status] = ...
    NOT_INITIALIZED: ClassVar[Status] = ...
    NOT_SUPPORTED: ClassVar[Status] = ...
    SUCCESS: ClassVar[Status] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str:
        """Convert to a string according to format_spec."""

class cuDSSError(Exception):
    """cuDSSError(status)"""
    def __init__(self, status) -> Any:
        """Initialize self.  See help(type(self)) for accurate signature."""
    def __reduce__(self) -> Any:
        """cuDSSError.__reduce__(self)"""
