# Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0
#
# This code was automatically generated across versions from 25.5 to 26.5, generator version 0.3.1.dev1723+geb5f29ab4. Do not modify it directly.

from ..cyblas cimport *


###############################################################################
# Wrapper functions
###############################################################################

cdef int _MKL_mkl_set_num_threads_local(int nth) except?-42 nogil
cdef void _MKL_mkl_set_num_threads(int nth) except* nogil
cdef void _openblas_openblas_set_num_threads(int num_threads) except* nogil
cdef int _openblas_openblas_set_num_threads_local(int num_threads) except?-42 nogil
cdef int _nvpl_blas_get_version() except?-42 nogil
cdef int _nvpl_blas_get_max_threads() except?-42 nogil
cdef void _nvpl_blas_set_num_threads(int nthr) except* nogil
cdef int _nvpl_blas_set_num_threads_local(int nthr_local) except?-42 nogil
cdef void _cblas_sgemv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const float alpha, const float* A, const nvpl_int_t lda, const float* X, const nvpl_int_t incX, const float beta, float* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_sgbmv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t KL, const nvpl_int_t KU, const float alpha, const float* A, const nvpl_int_t lda, const float* X, const nvpl_int_t incX, const float beta, float* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_strmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const float* A, const nvpl_int_t lda, float* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_stbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const float* A, const nvpl_int_t lda, float* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_stpmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const float* Ap, float* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_strsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const float* A, const nvpl_int_t lda, float* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_stbsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const float* A, const nvpl_int_t lda, float* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_stpsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const float* Ap, float* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_dgemv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const double alpha, const double* A, const nvpl_int_t lda, const double* X, const nvpl_int_t incX, const double beta, double* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_dgbmv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t KL, const nvpl_int_t KU, const double alpha, const double* A, const nvpl_int_t lda, const double* X, const nvpl_int_t incX, const double beta, double* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_dtrmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const double* A, const nvpl_int_t lda, double* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_dtbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const double* A, const nvpl_int_t lda, double* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_dtpmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const double* Ap, double* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_dtrsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const double* A, const nvpl_int_t lda, double* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_dtbsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const double* A, const nvpl_int_t lda, double* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_dtpsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const double* Ap, double* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_cgemv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_cgbmv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t KL, const nvpl_int_t KU, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_ctrmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ctbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ctpmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* Ap, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ctrsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ctbsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ctpsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* Ap, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_zgemv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_zgbmv(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t KL, const nvpl_int_t KU, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_ztrmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ztbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ztpmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* Ap, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ztrsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ztbsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const nvpl_int_t K, const void* A, const nvpl_int_t lda, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ztpsv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t N, const void* Ap, void* X, const nvpl_int_t incX) except* nogil
cdef void _cblas_ssymv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const float* A, const nvpl_int_t lda, const float* X, const nvpl_int_t incX, const float beta, float* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_ssbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const nvpl_int_t K, const float alpha, const float* A, const nvpl_int_t lda, const float* X, const nvpl_int_t incX, const float beta, float* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_sspmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const float* Ap, const float* X, const nvpl_int_t incX, const float beta, float* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_sger(const CBLAS_ORDER order, const nvpl_int_t M, const nvpl_int_t N, const float alpha, const float* X, const nvpl_int_t incX, const float* Y, const nvpl_int_t incY, float* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_ssyr(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const float* X, const nvpl_int_t incX, float* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_sspr(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const float* X, const nvpl_int_t incX, float* Ap) except* nogil
cdef void _cblas_ssyr2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const float* X, const nvpl_int_t incX, const float* Y, const nvpl_int_t incY, float* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_sspr2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const float* X, const nvpl_int_t incX, const float* Y, const nvpl_int_t incY, float* A) except* nogil
cdef void _cblas_dsymv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const double* A, const nvpl_int_t lda, const double* X, const nvpl_int_t incX, const double beta, double* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_dsbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const nvpl_int_t K, const double alpha, const double* A, const nvpl_int_t lda, const double* X, const nvpl_int_t incX, const double beta, double* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_dspmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const double* Ap, const double* X, const nvpl_int_t incX, const double beta, double* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_dger(const CBLAS_ORDER order, const nvpl_int_t M, const nvpl_int_t N, const double alpha, const double* X, const nvpl_int_t incX, const double* Y, const nvpl_int_t incY, double* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_dsyr(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const double* X, const nvpl_int_t incX, double* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_dspr(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const double* X, const nvpl_int_t incX, double* Ap) except* nogil
cdef void _cblas_dsyr2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const double* X, const nvpl_int_t incX, const double* Y, const nvpl_int_t incY, double* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_dspr2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const double* X, const nvpl_int_t incX, const double* Y, const nvpl_int_t incY, double* A) except* nogil
cdef void _cblas_chemv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_chbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_chpmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* Ap, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_cgeru(const CBLAS_ORDER order, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_cgerc(const CBLAS_ORDER order, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_cher(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const void* X, const nvpl_int_t incX, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_chpr(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const float alpha, const void* X, const nvpl_int_t incX, void* A) except* nogil
cdef void _cblas_cher2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_chpr2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* Ap) except* nogil
cdef void _cblas_zhemv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_zhbmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_zhpmv(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* Ap, const void* X, const nvpl_int_t incX, const void* beta, void* Y, const nvpl_int_t incY) except* nogil
cdef void _cblas_zgeru(const CBLAS_ORDER order, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_zgerc(const CBLAS_ORDER order, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_zher(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const void* X, const nvpl_int_t incX, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_zhpr(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const double alpha, const void* X, const nvpl_int_t incX, void* A) except* nogil
cdef void _cblas_zher2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* A, const nvpl_int_t lda) except* nogil
cdef void _cblas_zhpr2(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int_t N, const void* alpha, const void* X, const nvpl_int_t incX, const void* Y, const nvpl_int_t incY, void* Ap) except* nogil
cdef void _cblas_sgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const float alpha, const float* A, const nvpl_int_t lda, const float* B, const nvpl_int_t ldb, const float beta, float* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_ssymm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int_t M, const nvpl_int_t N, const float alpha, const float* A, const nvpl_int_t lda, const float* B, const nvpl_int_t ldb, const float beta, float* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_ssyrk(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const float alpha, const float* A, const nvpl_int_t lda, const float beta, float* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_ssyr2k(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const float alpha, const float* A, const nvpl_int_t lda, const float* B, const nvpl_int_t ldb, const float beta, float* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_strmm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const float alpha, const float* A, const nvpl_int_t lda, float* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_strsm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const float alpha, const float* A, const nvpl_int_t lda, float* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_dgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const double alpha, const double* A, const nvpl_int_t lda, const double* B, const nvpl_int_t ldb, const double beta, double* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_dsymm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int_t M, const nvpl_int_t N, const double alpha, const double* A, const nvpl_int_t lda, const double* B, const nvpl_int_t ldb, const double beta, double* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_dsyrk(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const double alpha, const double* A, const nvpl_int_t lda, const double beta, double* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_dsyr2k(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const double alpha, const double* A, const nvpl_int_t lda, const double* B, const nvpl_int_t ldb, const double beta, double* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_dtrmm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const double alpha, const double* A, const nvpl_int_t lda, double* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_dtrsm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const double alpha, const double* A, const nvpl_int_t lda, double* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_cgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_csymm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_csyrk(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_csyr2k(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_ctrmm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, void* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_ctrsm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, void* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_zgemm(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_zsymm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_zsyrk(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_zsyr2k(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_ztrmm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, void* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_ztrsm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, void* B, const nvpl_int_t ldb) except* nogil
cdef void _cblas_chemm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_cherk(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const float alpha, const void* A, const nvpl_int_t lda, const float beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_cher2k(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const float beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_zhemm(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int_t M, const nvpl_int_t N, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_zherk(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const double alpha, const void* A, const nvpl_int_t lda, const double beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_zher2k(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const double beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_sgemm_batch(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int_t* M_array, nvpl_int_t* N_array, nvpl_int_t* K_array, const float* alpha_array, const float** A_array, nvpl_int_t* lda_array, const float** B_array, nvpl_int_t* ldb_array, const float* beta_array, float** C_array, nvpl_int_t* ldc_array, nvpl_int_t group_count, nvpl_int_t* group_size) except* nogil
cdef void _cblas_dgemm_batch(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int_t* M_array, nvpl_int_t* N_array, nvpl_int_t* K_array, const double* alpha_array, const double** A_array, nvpl_int_t* lda_array, const double** B_array, nvpl_int_t* ldb_array, const double* beta_array, double** C_array, nvpl_int_t* ldc_array, nvpl_int_t group_count, nvpl_int_t* group_size) except* nogil
cdef void _cblas_cgemm_batch(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int_t* M_array, nvpl_int_t* N_array, nvpl_int_t* K_array, const void* alpha_array, const void** A_array, nvpl_int_t* lda_array, const void** B_array, nvpl_int_t* ldb_array, const void* beta_array, void** C_array, nvpl_int_t* ldc_array, nvpl_int_t group_count, nvpl_int_t* group_size) except* nogil
cdef void _cblas_zgemm_batch(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int_t* M_array, nvpl_int_t* N_array, nvpl_int_t* K_array, const void* alpha_array, const void** A_array, nvpl_int_t* lda_array, const void** B_array, nvpl_int_t* ldb_array, const void* beta_array, void** C_array, nvpl_int_t* ldc_array, nvpl_int_t group_count, nvpl_int_t* group_size) except* nogil
cdef void _cblas_sgemm_batch_strided(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const float alpha, const float* A, const nvpl_int_t lda, const nvpl_int_t stridea, const float* B, const nvpl_int_t ldb, const nvpl_int_t strideb, const float beta, float* C, const nvpl_int_t ldc, const nvpl_int_t stridec, const nvpl_int_t batch_size) except* nogil
cdef void _cblas_dgemm_batch_strided(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const double alpha, const double* A, const nvpl_int_t lda, const nvpl_int_t stridea, const double* B, const nvpl_int_t ldb, const nvpl_int_t strideb, const double beta, double* C, const nvpl_int_t ldc, const nvpl_int_t stridec, const nvpl_int_t batch_size) except* nogil
cdef void _cblas_cgemm_batch_strided(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const nvpl_int_t stridea, const void* B, const nvpl_int_t ldb, const nvpl_int_t strideb, const void* beta, void* C, const nvpl_int_t ldc, const nvpl_int_t stridec, const nvpl_int_t batch_size) except* nogil
cdef void _cblas_zgemm_batch_strided(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t M, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const nvpl_int_t stridea, const void* B, const nvpl_int_t ldb, const nvpl_int_t strideb, const void* beta, void* C, const nvpl_int_t ldc, const nvpl_int_t stridec, const nvpl_int_t batch_size) except* nogil
cdef void _cblas_sgemmt(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t N, const nvpl_int_t K, const float alpha, const float* A, const nvpl_int_t lda, const float* B, const nvpl_int_t ldb, const float beta, float* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_dgemmt(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t N, const nvpl_int_t K, const double alpha, const double* A, const nvpl_int_t lda, const double* B, const nvpl_int_t ldb, const double beta, double* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_cgemmt(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_zgemmt(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int_t N, const nvpl_int_t K, const void* alpha, const void* A, const nvpl_int_t lda, const void* B, const nvpl_int_t ldb, const void* beta, void* C, const nvpl_int_t ldc) except* nogil
cdef void _cblas_sgemv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const float alpha, const float* A, const nvpl_int64_t lda, const float* X, const nvpl_int64_t incX, const float beta, float* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_sgbmv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t KL, const nvpl_int64_t KU, const float alpha, const float* A, const nvpl_int64_t lda, const float* X, const nvpl_int64_t incX, const float beta, float* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_strmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const float* A, const nvpl_int64_t lda, float* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_stbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const float* A, const nvpl_int64_t lda, float* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_stpmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const float* Ap, float* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_strsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const float* A, const nvpl_int64_t lda, float* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_stbsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const float* A, const nvpl_int64_t lda, float* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_stpsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const float* Ap, float* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_dgemv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const double alpha, const double* A, const nvpl_int64_t lda, const double* X, const nvpl_int64_t incX, const double beta, double* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_dgbmv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t KL, const nvpl_int64_t KU, const double alpha, const double* A, const nvpl_int64_t lda, const double* X, const nvpl_int64_t incX, const double beta, double* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_dtrmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const double* A, const nvpl_int64_t lda, double* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_dtbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const double* A, const nvpl_int64_t lda, double* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_dtpmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const double* Ap, double* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_dtrsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const double* A, const nvpl_int64_t lda, double* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_dtbsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const double* A, const nvpl_int64_t lda, double* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_dtpsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const double* Ap, double* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_cgemv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_cgbmv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t KL, const nvpl_int64_t KU, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_ctrmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ctbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ctpmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* Ap, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ctrsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ctbsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ctpsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* Ap, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_zgemv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_zgbmv_64(const CBLAS_ORDER order, const CBLAS_TRANSPOSE TransA, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t KL, const nvpl_int64_t KU, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_ztrmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ztbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ztpmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* Ap, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ztrsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ztbsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const nvpl_int64_t K, const void* A, const nvpl_int64_t lda, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ztpsv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t N, const void* Ap, void* X, const nvpl_int64_t incX) except* nogil
cdef void _cblas_ssymv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const float* A, const nvpl_int64_t lda, const float* X, const nvpl_int64_t incX, const float beta, float* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_ssbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const nvpl_int64_t K, const float alpha, const float* A, const nvpl_int64_t lda, const float* X, const nvpl_int64_t incX, const float beta, float* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_sspmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const float* Ap, const float* X, const nvpl_int64_t incX, const float beta, float* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_sger_64(const CBLAS_ORDER order, const nvpl_int64_t M, const nvpl_int64_t N, const float alpha, const float* X, const nvpl_int64_t incX, const float* Y, const nvpl_int64_t incY, float* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_ssyr_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const float* X, const nvpl_int64_t incX, float* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_sspr_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const float* X, const nvpl_int64_t incX, float* Ap) except* nogil
cdef void _cblas_ssyr2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const float* X, const nvpl_int64_t incX, const float* Y, const nvpl_int64_t incY, float* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_sspr2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const float* X, const nvpl_int64_t incX, const float* Y, const nvpl_int64_t incY, float* A) except* nogil
cdef void _cblas_dsymv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const double* A, const nvpl_int64_t lda, const double* X, const nvpl_int64_t incX, const double beta, double* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_dsbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const nvpl_int64_t K, const double alpha, const double* A, const nvpl_int64_t lda, const double* X, const nvpl_int64_t incX, const double beta, double* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_dspmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const double* Ap, const double* X, const nvpl_int64_t incX, const double beta, double* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_dger_64(const CBLAS_ORDER order, const nvpl_int64_t M, const nvpl_int64_t N, const double alpha, const double* X, const nvpl_int64_t incX, const double* Y, const nvpl_int64_t incY, double* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_dsyr_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const double* X, const nvpl_int64_t incX, double* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_dspr_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const double* X, const nvpl_int64_t incX, double* Ap) except* nogil
cdef void _cblas_dsyr2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const double* X, const nvpl_int64_t incX, const double* Y, const nvpl_int64_t incY, double* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_dspr2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const double* X, const nvpl_int64_t incX, const double* Y, const nvpl_int64_t incY, double* A) except* nogil
cdef void _cblas_chemv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_chbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_chpmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* Ap, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_cgeru_64(const CBLAS_ORDER order, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_cgerc_64(const CBLAS_ORDER order, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_cher_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const void* X, const nvpl_int64_t incX, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_chpr_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const float alpha, const void* X, const nvpl_int64_t incX, void* A) except* nogil
cdef void _cblas_cher2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_chpr2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* Ap) except* nogil
cdef void _cblas_zhemv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_zhbmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_zhpmv_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* Ap, const void* X, const nvpl_int64_t incX, const void* beta, void* Y, const nvpl_int64_t incY) except* nogil
cdef void _cblas_zgeru_64(const CBLAS_ORDER order, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_zgerc_64(const CBLAS_ORDER order, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_zher_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const void* X, const nvpl_int64_t incX, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_zhpr_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const double alpha, const void* X, const nvpl_int64_t incX, void* A) except* nogil
cdef void _cblas_zher2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* A, const nvpl_int64_t lda) except* nogil
cdef void _cblas_zhpr2_64(const CBLAS_ORDER order, const CBLAS_UPLO Uplo, const nvpl_int64_t N, const void* alpha, const void* X, const nvpl_int64_t incX, const void* Y, const nvpl_int64_t incY, void* Ap) except* nogil
cdef void _cblas_sgemm_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const float alpha, const float* A, const nvpl_int64_t lda, const float* B, const nvpl_int64_t ldb, const float beta, float* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_ssymm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int64_t M, const nvpl_int64_t N, const float alpha, const float* A, const nvpl_int64_t lda, const float* B, const nvpl_int64_t ldb, const float beta, float* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_ssyrk_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const float alpha, const float* A, const nvpl_int64_t lda, const float beta, float* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_ssyr2k_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const float alpha, const float* A, const nvpl_int64_t lda, const float* B, const nvpl_int64_t ldb, const float beta, float* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_strmm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const float alpha, const float* A, const nvpl_int64_t lda, float* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_strsm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const float alpha, const float* A, const nvpl_int64_t lda, float* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_dgemm_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const double alpha, const double* A, const nvpl_int64_t lda, const double* B, const nvpl_int64_t ldb, const double beta, double* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_dsymm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int64_t M, const nvpl_int64_t N, const double alpha, const double* A, const nvpl_int64_t lda, const double* B, const nvpl_int64_t ldb, const double beta, double* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_dsyrk_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const double alpha, const double* A, const nvpl_int64_t lda, const double beta, double* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_dsyr2k_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const double alpha, const double* A, const nvpl_int64_t lda, const double* B, const nvpl_int64_t ldb, const double beta, double* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_dtrmm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const double alpha, const double* A, const nvpl_int64_t lda, double* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_dtrsm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const double alpha, const double* A, const nvpl_int64_t lda, double* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_cgemm_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_csymm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_csyrk_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_csyr2k_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_ctrmm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, void* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_ctrsm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, void* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_zgemm_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_zsymm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_zsyrk_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_zsyr2k_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_ztrmm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, void* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_ztrsm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_DIAG Diag, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, void* B, const nvpl_int64_t ldb) except* nogil
cdef void _cblas_chemm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_cherk_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const float alpha, const void* A, const nvpl_int64_t lda, const float beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_cher2k_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const float beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_zhemm_64(const CBLAS_ORDER Order, const CBLAS_SIDE Side, const CBLAS_UPLO Uplo, const nvpl_int64_t M, const nvpl_int64_t N, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_zherk_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const double alpha, const void* A, const nvpl_int64_t lda, const double beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_zher2k_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE Trans, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const double beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_sgemmt_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t N, const nvpl_int64_t K, const float alpha, const float* A, const nvpl_int64_t lda, const float* B, const nvpl_int64_t ldb, const float beta, float* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_dgemmt_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t N, const nvpl_int64_t K, const double alpha, const double* A, const nvpl_int64_t lda, const double* B, const nvpl_int64_t ldb, const double beta, double* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_cgemmt_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_zgemmt_64(const CBLAS_ORDER Order, const CBLAS_UPLO Uplo, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const void* B, const nvpl_int64_t ldb, const void* beta, void* C, const nvpl_int64_t ldc) except* nogil
cdef void _cblas_sgemm_batch_64(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int64_t* M_array, nvpl_int64_t* N_array, nvpl_int64_t* K_array, const float* alpha_array, const float** A_array, nvpl_int64_t* lda_array, const float** B_array, nvpl_int64_t* ldb_array, const float* beta_array, float** C_array, nvpl_int64_t* ldc_array, nvpl_int64_t group_count, nvpl_int64_t* group_size) except* nogil
cdef void _cblas_dgemm_batch_64(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int64_t* M_array, nvpl_int64_t* N_array, nvpl_int64_t* K_array, const double* alpha_array, const double** A_array, nvpl_int64_t* lda_array, const double** B_array, nvpl_int64_t* ldb_array, const double* beta_array, double** C_array, nvpl_int64_t* ldc_array, nvpl_int64_t group_count, nvpl_int64_t* group_size) except* nogil
cdef void _cblas_cgemm_batch_64(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int64_t* M_array, nvpl_int64_t* N_array, nvpl_int64_t* K_array, const void* alpha_array, const void** A_array, nvpl_int64_t* lda_array, const void** B_array, nvpl_int64_t* ldb_array, const void* beta_array, void** C_array, nvpl_int64_t* ldc_array, nvpl_int64_t group_count, nvpl_int64_t* group_size) except* nogil
cdef void _cblas_zgemm_batch_64(CBLAS_ORDER Order, CBLAS_TRANSPOSE* TransA_array, CBLAS_TRANSPOSE* TransB_array, nvpl_int64_t* M_array, nvpl_int64_t* N_array, nvpl_int64_t* K_array, const void* alpha_array, const void** A_array, nvpl_int64_t* lda_array, const void** B_array, nvpl_int64_t* ldb_array, const void* beta_array, void** C_array, nvpl_int64_t* ldc_array, nvpl_int64_t group_count, nvpl_int64_t* group_size) except* nogil
cdef void _cblas_sgemm_batch_strided_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const float alpha, const float* A, const nvpl_int64_t lda, const nvpl_int64_t stridea, const float* B, const nvpl_int64_t ldb, const nvpl_int64_t strideb, const float beta, float* C, const nvpl_int64_t ldc, const nvpl_int64_t stridec, const nvpl_int64_t batch_size) except* nogil
cdef void _cblas_dgemm_batch_strided_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const double alpha, const double* A, const nvpl_int64_t lda, const nvpl_int64_t stridea, const double* B, const nvpl_int64_t ldb, const nvpl_int64_t strideb, const double beta, double* C, const nvpl_int64_t ldc, const nvpl_int64_t stridec, const nvpl_int64_t batch_size) except* nogil
cdef void _cblas_cgemm_batch_strided_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const nvpl_int64_t stridea, const void* B, const nvpl_int64_t ldb, const nvpl_int64_t strideb, const void* beta, void* C, const nvpl_int64_t ldc, const nvpl_int64_t stridec, const nvpl_int64_t batch_size) except* nogil
cdef void _cblas_zgemm_batch_strided_64(const CBLAS_ORDER Order, const CBLAS_TRANSPOSE TransA, const CBLAS_TRANSPOSE TransB, const nvpl_int64_t M, const nvpl_int64_t N, const nvpl_int64_t K, const void* alpha, const void* A, const nvpl_int64_t lda, const nvpl_int64_t stridea, const void* B, const nvpl_int64_t ldb, const nvpl_int64_t strideb, const void* beta, void* C, const nvpl_int64_t ldc, const nvpl_int64_t stridec, const nvpl_int64_t batch_size) except* nogil
